# fly.toml app configuration file generated for always-sunny-clock on 2025-03-13T16:18:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'always-sunny-clock'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  NODE_ENV = "production"
  # Add other environment variables your app needs
